DROP TABLE IF EXISTS inspirations;
DROP TABLE IF EXISTS art_inst;
DROP TABLE IF EXISTS artists;
DROP TABLE IF EXISTS instruments;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS hometowns;

CREATE TABLE hometowns (
	hid SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	city VARCHAR(50) NOT NULL,
	country VARCHAR(50) NOT NULL,
	current_pop BIGINT UNSIGNED,
	PRIMARY KEY (hid),
	UNIQUE KEY (city, country)
)ENGINE=InnoDb DEFAULT CHARSET=utf8;

CREATE TABLE genres (
	gid SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	genre VARCHAR(50) NOT NULL,
	PRIMARY KEY (gid)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE instruments (
	iid SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	instrument VARCHAR(50) NOT NULL,
	PRIMARY KEY (iid),
	UNIQUE KEY (instrument)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE artists (
	aid SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	fname VARCHAR(50) NOT NULL,
	lname VARCHAR(50) NOT NULL,
	hometown SMALLINT UNSIGNED NOT NULL,
	genre SMALLINT UNSIGNED NOT NULL,
	PRIMARY KEY (aid),
	UNIQUE KEY (fname, lname),
	KEY idx_fk_hometown (hometown),
	KEY idx_fk_genre (genre),
	CONSTRAINT `fk_hometown` FOREIGN KEY (hometown) REFERENCES hometowns (hid) 
		ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT `fk_genre` FOREIGN KEY (genre) REFERENCES genres (gid) 
		ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE art_inst (
	ai_aid SMALLINT UNSIGNED NOT NULL,
	ai_iid SMALLINT UNSIGNED NOT NULL,
	main BOOLEAN NOT NULL DEFAULT FALSE, 
	PRIMARY KEY (ai_aid, ai_iid),
	CONSTRAINT `fk_art_inst_ai_aid` FOREIGN KEY (ai_aid) REFERENCES artists (aid) 
		ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT `fk_art_inst_ai_iid` FOREIGN KEY (ai_iid) REFERENCES instruments (iid) 
		ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE inspirations (
	luminary SMALLINT UNSIGNED NOT NULL,
	inspired SMALLINT UNSIGNED NOT NULL,
	relationship VARCHAR(50),
	PRIMARY KEY (luminary, inspired),
	CONSTRAINT `fk_inspirations_art1` FOREIGN KEY (luminary) REFERENCES artists (aid) 
		ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT `fk_inspirations_art2` FOREIGN KEY (inspired) REFERENCES artists (aid) 
		ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
